allowBuilds:
  canvas: true
  esbuild: true
  libpq: true
minimumReleaseAgeExclude:
  - '@types/node@22.19.20'
  - mysql2@3.22.5
  - '@rian8337/osu-base@4.0.0-beta.90'
  - '@rian8337/osu-difficulty-calculator@4.0.0-beta.90'
  - '@rian8337/osu-droid-replay-analyzer@4.0.0-beta.90'
  - '@rian8337/osu-droid-utilities@4.0.0-beta.90'
  - '@rian8337/osu-rebalance-difficulty-calculator@4.0.0-beta.90'
  - '@rian8337/osu-strain-graph-generator@4.0.0-beta.90'
onlyBuiltDependencies:
  - canvas
  - esbuild
  - libpq
